export const GAME_TUNING = {
  player: {
    speed: 6.15,
    radius: 0.5,
    startY: 0.42,
  },
  arena: {
    width: 7.6,
    depth: 7.6,
  },
  difficulty: {
    rampSeconds: 48,
    startFallSpeed: 3.75,
    maxFallSpeed: 6.15,
    startSpawnInterval: 0.66,
    minSpawnInterval: 0.38,
    startMaxObstacles: 16,
    maxObstacles: 30,
  },
  score: {
    pointsPerSecond: 12,
    pointsPerDodge: 35,
  },
  visuals: {
    maxRenderedObstacles: 36,
    warningStartY: 5.8,
    warningFullY: 1.1,
    cameraShakeSeconds: 0.22,
    doodleOutlineScale: 1.08,
    doodleWarningDashCount: 12,
    doodlePlayerBob: 0.014,
    doodlePlayerRunBob: 0.036,
  },
  fun: {
    closeCallNiceDistance: 1.35,
    closeCallCloseDistance: 1.0,
    closeCallPanicDistance: 0.74,
    closeCallVerticalWindowMinY: -0.85,
    closeCallVerticalWindowMaxY: 1.15,
    comboTimeoutSeconds: 3.2,
    comboMultiplierCap: 4,
    closeCallBonus: {
      nice: 20,
      close: 45,
      panic: 80,
    },
    shieldSpawnFirstSeconds: 11,
    shieldSpawnIntervalSeconds: 16,
    shieldPickupRadius: 0.78,
    shieldPickupExpiresSeconds: 9,
  },
  feel: {
    shieldAttractRadius: 1.55,
    shieldCollectRadius: 1.12,
    shieldSaveFreezeSeconds: 0.18,
    shieldSaveBurstSeconds: 0.62,
    shieldSaveClearRadius: 1.75,
    closeCallPulseSeconds: 0.62,
    panicComboSummaryMinimum: 3,
  },
} as const;
